Repository calblueprint/meepanyar, pull requests merged in 2020-12, with the labels that each got.

#16 Tiffany/customer records func + makestyles
  package-lock.json
  package.json
  src/App.tsx
  src/components/BaseComponents/BaseHeader.tsx
  src/components/Button.tsx
  src/components/Checkbox.tsx
  src/components/CustomerRecords/Record.tsx
  src/components/CustomerRecords/TabMenu.tsx
  src/components/OutlinedCardList.tsx
  src/components/TextField.tsx
  src/screens/Customers/AddCustomer.tsx
  src/screens/Customers/AddMeterReading.tsx
  src/screens/Customers/CustomerProfile.tsx
  src/screens/Customers/CustomerRecords.tsx
  src/screens/Customers/EditCustomer.tsx
  src/screens/Errors.tsx
  src/screens/Login.tsx
  src/screens/Shopping.tsx
  src/screens/Tools.tsx
  src/styles/CustomerStyles.ts
  src/styles/MenuStyle.ts
  src/styles/ThemeStyles.ts
Labels: requested changes

#14 Financial Summary Screens
  src/App.tsx
  src/components/BaseComponents/BottomNav.tsx
  src/components/TextWrapper.tsx
  src/screens/Errors.tsx
  src/screens/FinancialSummary/ConfirmDialog.tsx
  src/screens/FinancialSummary/ConfirmDialogContents.tsx
  src/screens/FinancialSummary/FinancialSummary.tsx
  src/screens/Shopping.tsx
  src/screens/Tools.tsx
  src/styles/CustomerStyles.ts
  src/styles/MenuStyle.ts
  src/styles/ThemeStyles.ts
Labels: approved

#22 Clean-up and Base Components
  src/App.css
  src/App.tsx
  src/components/BaseComponents/BaseHeader.tsx
  src/components/BaseComponents/BaseNavigation.tsx
  src/components/BaseComponents/BaseScreen.tsx
  src/components/BaseComponents/BaseScrollView.tsx
  src/components/BaseComponents/BottomNav.tsx
  src/components/OutlinedCardList.tsx
  src/index.css
  src/index.tsx
  src/screens/Customers/AddCustomer.tsx
  src/screens/Customers/AddMeterReading.tsx
  src/screens/Customers/CustomerProfile.tsx
  src/screens/Customers/CustomerRecords.tsx
  src/screens/Customers/EditCustomer.tsx
  src/screens/Customers/components/Record.tsx
  src/screens/Customers/components/TabMenu.tsx
  src/screens/FinancialSummary/FinancialSummary.tsx
  src/screens/FinancialSummary/components/ConfirmDialog.tsx
  src/screens/FinancialSummary/components/ConfirmDialogContents.tsx
  src/styles/LoginStyles.ts
Labels: ready for review

#19 Meter Readings, Payments, and Customer Creation offline
  package-lock.json
  package.json
  src/lib/redux/userData.ts
  src/screens/Home.tsx
  src/sw-custom.js
  src/utils/customerUtils.js
  src/utils/new-schema/airtable.js
  src/utils/new-schema/request.js
  src/utils/new-schema/schema.js
Labels: ready for review

#24 Updated home page styling
  package-lock.json
  package.json
  src/App.tsx
  src/components/BaseComponents/BaseHeader.tsx
  src/lib/redux/siteData.ts
  src/screens/FinancialSummary/FinancialSummary.tsx
  src/screens/Home.tsx
  src/screens/Home/Home.tsx
  src/screens/Home/components/HomeMenuItem.tsx
  src/screens/Home/components/SiteMenu.tsx
  src/styles/BottomNavStyles.ts
Labels: approved
