Repository calblueprint/meepanyar, pull requests merged in 2021-01, with the labels that each got.

#26 Cleanup airtable ts files
  package.json
  src/lib/airlock/airlock.ts
  src/lib/airtable/airtable.js
  src/lib/airtable/interface.ts
  src/lib/airtable/request.js
  src/lib/airtable/schema.js
  src/lib/redux/siteData.ts
  src/lib/utils/customerUtils.js
  src/screens/Customers/CustomerMain.tsx
  src/screens/Customers/CustomerProfile.tsx
  src/screens/Customers/CustomerRecords.tsx
  src/screens/Customers/components/TabMenu.tsx
  src/screens/FinancialSummary/FinancialSummary.tsx
  src/screens/Home/Home.tsx
  src/screens/Home/components/SiteMenu.tsx
  src/utils/airtable/airtable.ts
  src/utils/airtable/requests.ts
  src/utils/airtable/schema.ts
  src/utils/new-schema/airtable.js
Labels: approved, ready for review

#27 Moved API calls to meter readings and payments to backend
  src/lib/airtable/patches/0001-Patch-commit.-Site-schema-contains-customer-field-in.patch
  src/lib/airtable/patches/README.md
  src/lib/airtable/schema.js
  src/lib/redux/siteData.ts
  src/lib/redux/userData.ts
Labels: approved, ready for review

#9 Kyle/customers
  .eslintrc
  package-lock.json
  package.json
  src/components/CustomerCard.tsx
  src/components/UserSearchBar.tsx
  src/lib/utils/TrieTree.ts
  src/screens/Customers/CustomerMain.tsx
Labels: requested changes

#25 Added loading screen until data is finished being fetched
  src/components/BaseComponents/LoadingComponent.tsx
  src/components/authentication/AuthenticatedRoute.tsx
Labels: approved, ready for review

#28 Cleaned up env file and service worker uses environment file for network endpoint
  .env.example
  package.json
  src/custom-sw/sw-build.js
  src/custom-sw/sw-custom.js
  src/custom-sw/sw-env.js
Labels: ready for review
