Repository calblueprint/meepanyar, pull requests merged in 2021-02, with the labels that each got.

#30 Changed route names to be kebab-case and work with offline
  src/App.tsx
  src/screens/Customers/CustomerMain.tsx
  src/screens/Customers/CustomerProfile.tsx
  src/screens/Home/Home.tsx
Labels: ready for review

#32 Profile dropdown and logout functionality
  src/components/BaseComponents/BaseHeader.tsx
  src/lib/airlock/airlock.ts
  src/lib/redux/userData.ts
  src/lib/redux/userDataSlice.ts
Labels: approved

#29 Regenerate Airtable schema and updated patch README
  src/lib/airtable/patches/0001-Patch-commit.-Site-schema-contains-customer-field-in.patch
  src/lib/airtable/patches/README.md
  src/lib/airtable/patches/patch-01.patch
  src/lib/airtable/request.js
  src/lib/airtable/schema.js
Labels: approved

#34 Add Customer FAB
  src/screens/Customers/CustomerMain.tsx
Labels: approved

#20 Tiffany/submitted records
  package-lock.json
  package.json
  src/App.tsx
  src/components/BaseComponents/BaseScrollView.tsx
  src/components/OutlinedCardList.tsx
  src/components/TextField.tsx
  src/lib/airtable/schema.js
  src/screens/Customers/AddCustomer.tsx
  src/screens/Customers/AddMeterReading.tsx
  src/screens/Customers/CustomerProfile.tsx
  src/screens/Customers/EditCustomer.tsx
  src/screens/FinancialSummary/FinancialSummariesMain.tsx
Labels: approved

#35 Customer Overview Sorting and Filtering
  src/screens/Customers/CustomerMain.tsx
Labels: approved

#21 Tiffany/customer data with redux
  src/components/OutlinedCardList.tsx
  src/lib/airtable/interface.ts
  src/lib/airtable/request.js
  src/lib/moment/momentUtils.ts
  src/lib/redux/siteDataSlice.ts
  src/lib/utils/customerUtils.ts
  src/lib/utils/offlineUtils.js
  src/screens/Customers/CustomerMain.tsx
  src/screens/Customers/CustomerProfile.tsx
Labels: requested changes
